FilterProcessor: Fix predicate assembling for `EXISTS` and `NOT EXISTS` operators
Icinga/ipl-sql pull request #87
Opened 2024-06-19 12:46 UTC by raviks789

fix #86

2024-06-24 08:43 UTC, nilmerg commented
Please show a stacktrace.

2024-06-24 08:50 UTC, raviks789 commented
> Please show a stacktrace.
Check the below screenshot.

![Screenshot 2024-06-24 at 10 46 48](https://github.com/Icinga/ipl-sql/assets/33730024/163b15fc-d8a5-4f66-aeed-3386f59a1c1a)

2024-06-24 10:53 UTC, nilmerg requested changes
Please add a test case for this.

2024-06-25 09:54 UTC, nilmerg approved these changes

2024-06-25 09:55 UTC, merged